### PR TITLE
Feature/balance sheet

### PR DESCRIPTION
**Pull request by rockingrohit9639**
- Fetching and showing the user's physical assets
- Add feature to create a new asset

### CODE REVIEW

**Comment by mohitkhatri06** [comment]
Screenshot_20231105-120448_Expo Go
Getting the following

**Comment by rockingrohit9639** [comment]
@mohitkhatri06 Can you please try again? I have pushed one commit.

**Comment by mohitkhatri06** [comment]
not able to log in  getting the following Error
image

**Comment by rockingrohit9639** [comment]
> not able to log in getting the following Error image

This is just a `warning`, this cannot stop you from logging in....can you find any other error?

**Comment by mohitkhatri06** [comment]
No I did not got any other error, but login button was not working. I was not able to proceed after the creds

**Comment by bharathkumarchowdary** [comment]
I'm too seeing error on this PR
Following is command line log

`Error: Duplicated files or mocks. Please check the console for more info
    at setModule (/Users/bharathkumargundala/code/lekkalu-app/node_modules/metro-file-map/src/index.js:450:17)
    at workerReply (/Users/bharathkumargundala/code/lekkalu-app/node_modules/metro-file-map/src/index.js:507:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at async HasteMap._applyFileDelta (/Users/bharathkumargundala/code/lekkalu-app/node_modules/metro-file-map/src/index.js:672:7)
    at async /Users/bharathkumargundala/code/lekkalu-app/node_modules/metro-file-map/src/index.js:327:9
    at async DependencyGraph.ready (/Users/bharathkumargundala/code/lekkalu-app/node_modules/metro/src/node-haste/DependencyGraph.js:95:5)
    at async Bundler.ready (/Users/bharathkumargundala/code/lekkalu-app/node_modules/metro/src/Bundler.js:69:5)
    at async IncrementalBundler.ready (/Users/bharathkumargundala/code/lekkalu-app/node_modules/metro/src/IncrementalBundler.js:289:5)
    at async Server.ready (/Users/bharathkumargundala/code/lekkalu-app/node_modules/metro/src/Server.js:1085:5)
`

Following is error on mobile screen on app

`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Duplicated files or mocks. Please check the console for more info<br> &nbsp; &nbsp;at setModule (/Users/bharathkumargundala/code/lekkalu-app/node_modules/metro-file-map/src/index.js:450:17)<br> &nbsp; &nbsp;at workerReply (/Users/bharathkumargundala/code/lekkalu-app/node_modules/metro-file-map/src/index.js:507:9)<br> &nbsp; &nbsp;at process.processTicksAndRejections (node:internal/process/task_queues:95:5)<br> &nbsp; &nbsp;at async Promise.all (index 2)<br> &nbsp; &nbsp;at async HasteMap._applyFileDelta (/Users/bharathkumargundala/code/lekkalu-app/node_modules/metro-file-map/src/index.js:672:7)<br> &nbsp; &nbsp;at async /Users/bharathkumargundala/code/lekkalu-app/node_modules/metro-file-map/src/index.js:327:9<br> &nbsp; &nbsp;at async DependencyGraph.ready (/Users/bharathkumargundala/code/lekkalu-app/node_modules/metro/src/node-haste/DependencyGraph.js:95:5)<br> &nbsp; &nbsp;at async Bundler.ready (/Users/bharathkumargundala/code/lekkalu-app/node_modules/metro/src/Bundler.js:69:5)<br> &nbsp; &nbsp;at async IncrementalBundler.ready (/Users/bharathkumargundala/code/lekkalu-app/node_modules/metro/src/IncrementalBundler.js:289:5)<br> &nbsp; &nbsp;at async Server.ready (/Users/bharathkumargundala/code/lekkalu-app/node_modules/metro/src/Server.js:1085:5)</pre>
</body>
</html>


ABI49_0_0RCTFatal
ABI49_0_0RCTConvertArrayValue
149FF9CD-3E92-321D-B92F-EF58717C70B6
149FF9CD-3E92-321D-B92F-EF58717C70B6
149FF9CD-3E92-321D-B92F-EF58717C70B6
_dispatch_main_queue_callback_4CF
CEB74A0C-5EA4-3F5A-9DE8-73F0DAD2F4CB
CEB74A0C-5EA4-3F5A-9DE8-73F0DAD2F4CB
CFRunLoopRunSpecific
GSEventRunModal
EC1206D7-B4C9-3257-BB63-08E26A802416
UIApplicationMain
main
0D856E72-9A63-3B5B-879F-8D026115A4F0
`

**Comment by mohitkhatri06** [comment]
@rockingrohit9639 please add a tab for the asset and the other one for liabilties

**Review by mohitkhatri06 — APPROVED** [review]

**Review by bharathkumarchowdary — APPROVED** [review]

**Pull request merged**
