### PR TITLE
Feature/budget flow

### PR DESCRIPTION
**Pull request by HitDoshi**
I have created the budget flow with API integration.

### CODE REVIEW

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
- [ ] The app is not showing budgets when clicked view all budgets even though "reacter" user has budgets set through web app and can be seen in admin panel
image
- [ ] While adding budget, Month should not be a datepicker but 2 different select pickers, one for year (2024, 2023, 2022 etc) and other for month (Feb, Jan, Dec etc). When doing a POST req to backend add -01 as date to the user selected year and month to add field "month" in endpoint

**Comment by mohitkhatri06** [comment]
@HitDoshi also in the list show year also along with the month

**Comment by HitDoshi** [comment]
Below are list of update which is updated:-

1. Add budget list refresh control feature
2. Add year & month at add budget and create month & year picker modal
3. Delete budget Optimistically
4. Show year along with the month

**Comment by HitDoshi** [comment]
Conflict resolved.

**Comment by bharathkumarchowdary** [comment]
@mohitkhatri06 I'm not able to see budgets, Please re-request when the PR is ready

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
image

**Comment by mohitkhatri06** [comment]
@bharathkumarchowdary for the android it is loading, it is OS related issue @HitDoshi please have a look over the code if there is something we are missing which is causing this behavior for the different OS.

**Comment by bharathkumarchowdary** [comment]
Please re-request review once the changes are finished

**Comment by HitDoshi** [comment]
The issue has been fixed now, and the code has been pushed. You can review the changes.

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
sort budget list according to time.. latest being top in the list

**Review by bharathkumarchowdary — APPROVED** [review]

**Comment by mohitkhatri06** [comment]
@HitDoshi rebase branch

**Comment by mohitkhatri06** [comment]
@HitDoshi while doing an update to the budget it is giving 400, as backend is not accepting the date format

**Comment by HitDoshi** [comment]
Screenshot_1710442126
Screenshot_1710442545

- Update UI like add floating button & show month, year on edit budget modal
- Fix Edit budget issue

**Review by mohitkhatri06 — APPROVED** [review]

**Pull request merged**
