### PR TITLE
Feature/user settings

### PR DESCRIPTION
**Pull request by rockingrohit9639**
- Create bottom navigation
- Create user settings page
- Create logout button on settings page

### CODE REVIEW

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
On the iOS Settings page, why does it look like this? why can't we have dedicated buttons/ui for the use to click whenever he wants to update his info/password?
image

**Comment by mohitkhatri06** [comment]
Screenshot_20231209-192844_Expo Go

The bottom navigation icons are not completely visible

**Comment by rockingrohit9639** [comment]
> Screenshot_20231209-192844_Expo Go
> 
> The bottom navigation icons are not completely visible

@mohitkhatri06 can you please check again. I have pushed some changes

**Comment by mohitkhatri06** [comment]
@rockingrohit9639 when click on the create expense clear the old state

**Review by mohitkhatri06 — APPROVED** [review]

**Review by bharathkumarchowdary — APPROVED** [review]

**Pull request merged**
