### PR TITLE
Feature: Goals with timeline span.

### PR DESCRIPTION
**Pull request by Sandip-Z**
To run this PR:
**For Android**
It should work with expo. 
`npm start ` would be enough.

**For Ios**
Since this PR uses native library which is not compatible with expo IOS, we need to build it:

Following files are required to build:
1. firebase/GoogleService-Info.plist
2. firebase/google-services.json

Make sure you have following things in your .env file:
`GOOGLE_SERVICES_JSON="firebase/google-services.json"`
`GOOGLE_SERVICES_PLIST="firebase/GoogleService-Info.plist"`

Then, build the app, and run ios in emulator using following commands.

`npx expo prebuild --clean` 
`npx expo run:ios`

Tasks in this PR:
- [x] Display Source name instead of id in goal detail page.
- [x] Reachable by can be shown in a better way.. Like if it is 49 days, it can be shown as Goal is reachable in 1.67 months. Likewise for weeks and years
- [x] Tabs for time span to display timeline data in day, week, month and year.
- [x] Default the timeline filter to min and max dates of available data
- [x]  The creation form of a Goal must have help text shown with appropriate tiny icons beside them

### CODE REVIEW

**Comment by bharathkumarchowdary** [comment]
It's not showing any goals
image

**Comment by bharathkumarchowdary** [comment]
Also please add one simple unit test for Goals

**Comment by Sandip-Z** [comment]
> It's not showing any goals 

You might be missing this in your .env file, can you please check
`EXPO_PUBLIC_API_V2_BASE_URL="https://api.finuncle.com/api/v2"`

**Comment by bharathkumarchowdary** [comment]
@Sandip-Z , Please re-request review once the PR is ready

**Comment by Sandip-Z** [comment]
> @Sandip-Z , Please re-request review once the PR is ready

Okay. I am refactoring the code.

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
I'm facing 2 errors while running expo
Simulator Screenshot - iPhone 15 Pro Max - 2024-03-08 at 17 55 12

**Comment by Sandip-Z** [comment]
@bharathkumarchowdary. This PR has new dependencies. Did you run npm install?

**Comment by bharathkumarchowdary** [comment]
> @bharathkumarchowdary. This PR has new dependencies. Did you run npm install?

Yes.. even with npm install, I'm seeing same issue

**Review by bharathkumarchowdary — APPROVED** [review]

**Review by mohitkhatri06 — APPROVED** [review]

**Pull request merged**
