### PR TITLE
Ledning Page

### PR DESCRIPTION
**Pull request by imhardikdesai**

### CODE REVIEW

**Comment by mohitkhatri06** [comment]
1. refetch is not happening after the creation and deletion. and after the successful creation of the acc there is no redirection or the message of the success.
2. position of the edit and delete is wrong, instead give a menu at each list item where they can see the edit and delete

**Comment by imhardikdesai** [comment]
> 2. position of the edit and delete is wrong, instead give a menu at each list item where they can see the edit and delete

we can use this https://tamagui.dev/ui/popover?subpath=popover. because in UI library menu is not avalible

**Comment by imhardikdesai** [comment]
@mohitkhatri06 added new changes
- added notation for required fields

**Comment by mohitkhatri06** [comment]
@imhardikdesai we are using popover in income statement, and also are we showing the error messages from the backend to the frontend?
for example if the account is already exited

**Comment by imhardikdesai** [comment]
@mohitkhatri06 @bharathkumarchowdary 
I have added error handling for all lending API calls. also i have replace old edit, delete actions with menu

**Review by bharathkumarchowdary — APPROVED** [review]
Wait for @mohitkhatri06 's approval for merging

**Comment by imhardikdesai** [comment]
@bharathkumarchowdary @mohitkhatri06 
- user can now click on lending card for navigate to account list

**Review by bharathkumarchowdary — APPROVED** [review]

**Review by mohitkhatri06 — APPROVED** [review]

**Pull request merged**
