### PR TITLE
Scenarios UI

### PR DESCRIPTION
**Pull request by Sandip-Z**

### CODE REVIEW

**Comment by mohitkhatri06** [comment]
@Sandip-Z rebase this branch as it is still under process I wanted to have a look over it I am getting the following error
image

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
1. Inside an asset, dates are shown clipped vertically image
2. Edit an asset with sell value 'abcd' does not show any validation error. It should not allow me to place text in the number field in the first place
3. Expense type is not shown in the field even after selection
4. Deleting a scenario does not ask for confirmation. it is fundamental for any delete functionality in any UI/UX
5. There is no share button for a scenario anywhere. We need to add it somewhere
6. Adding objects inside a scenario still doesn't show up good on the app. 
image

**Review by bharathkumarchowdary — DISMISSED** [review]
Let's wait for @mohitkhatri06 's approval for merging

**Comment by mohitkhatri06** [comment]
@Sandip-Z while creating the assets, liability, show the star mark for the required field, if any empty show the error just below that field.
whatever error message gettign from the backend show at the bottom of the form, using the red text small
when doing post/update loader in the button

**Comment by bharathkumarchowdary** [comment]
@Sandip-Z .. There are conflicts on this PR to resolve

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
Can you upgrade react-native to 0.72.10 with this PR @Sandip-Z 
Also, why does it show scenarios when not logged in?
image

**Review by bharathkumarchowdary — DISMISSED** [review]

**Review by bharathkumarchowdary — APPROVED** [review]

**Pull request merged**
