### PR TITLE
Integrate EMI Calculator & Add Dark mode support for app

### PR DESCRIPTION
**Pull request by Snehal018**

### CODE REVIEW

**Comment by bharathkumarchowdary** [comment]
@Snehal018 
Does the feature work both on android and ios simulators?

**Comment by Snehal018** [comment]
@bharathkumarchowdary, Yes

**Review by rockingrohit9639 — DISMISSED** [review]
- For the next time please avoid using `native-base` and use `tamagui` only. In future we will remote `native-base` completely from the project.

**Comment by Snehal018** [comment]
@rockingrohit9639 , sure i will keep it in mind, btw i think the only place i have used native-base component is for popover component, that is because current popover implementation by tamagui is very broken, it lags on iOS and doesn't work at all for android, is there is any other where i have used native-base then please let me know.

Screenshot 2024-01-11 at 1 36 49 PM

**Comment by rockingrohit9639** [comment]
Okay @Snehal018
it is good for now... we will find out an alternative or we will create our own popover later when we will remove native-base

**Comment by rockingrohit9639** [comment]
@Snehal018 I realized one more thing about your code. 
Instead of using `val` directly for getting theme values use `get()` as tries to gives the optimized values. 

For example -> `theme.color.value` -> `theme.color.get()`

And also, use `tamagui` component API to style them, dont create stylesheets explicitly.

**Review by bharathkumarchowdary — DISMISSED** [review]

**Review by bharathkumarchowdary — APPROVED** [review]

**Review by mohitkhatri06 — DISMISSED** [review]

**Review by bharathkumarchowdary — APPROVED** [review]

**Review by mohitkhatri06 — APPROVED** [review]

**Pull request merged**
