### PR TITLE
Expo upgrade

### PR DESCRIPTION
**Pull request by bharathkumarchowdary**

### CODE REVIEW

**Comment by mohitkhatri06** [comment]
getting error when I use the command npx expo run:android
image

**Comment by bharathkumarchowdary** [comment]
@mohitkhatri06 , what is the command you gave to arrive at this error?

**Comment by mohitkhatri06** [comment]
@bharathkumarchowdary npx expo run:android

**Comment by bharathkumarchowdary** [comment]
@Sandip-Z , are you too getting same error as @mohitkhatri06 ?

**Comment by Sandip-Z** [comment]
@bharathkumarchowdary Expo SDK has been updated in PR #70. So I am closing this PR.

**Pull request closed without merging**
